server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka.springcloud.cn/eureka/
#    register-with-eureka: true
#    fetch-registry: true

spring:
  main:
    allow-bean-definition-overriding: true #@FeignClient(value = "服务名") 设置可以有多个类存在相同的FeignClient 中的value值
  application:
    name: client



#feign:
#  client:
#    config:
#      feignName:                                            #需要配置FeignClient的名字
#        connectTimeout: 5000                                #链接超时时间
#        readTimeout: 5000                                   #读超时时间
#        loggerLevel: full                                   #配置FeignClient的日志级别
#        errorDecoder: com.example.SimpleErrorDecoder        #错误解码器
#        retryer: com.example.SimpleRetryer                  #重试配置
#        requestInterceptors:                                #配置拦截器
#        - com.example.FooRequestInterceptor
#        - com.example.BarRequestInterceptor
#        decode404: false
#        encoder: com.example.SimpleEncoder                  #Feign编码器
#        decoder: com.example.SimpleDecoder                  #Feign解码器
#        contract: com.example.SimpleContract                #Feign的Contract链接


feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    demo.eureka.client: debug

##配置的方式指定轮询策略
provider:
  ribbon:
    #listOfServers: http://localhost:8082 #当eureka禁用的时候,手动指定的服务
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule



provider2:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

ribbon:
  eureka:
    enabled: true
