server:
  port: 8082


eureka:
  client:
    service-url:
      #      defaultZone: http://eureka.springcloud.cn/eureka/
      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true #注册到eureka
#    fetch-registry: true
spring:
  application:
    name: provider #指定服务的名称 这个服务名称可以给Feign来使用 , 作为路由


# dashboard - 放开 hystrix
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

